/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Getter
@Setter
@Transactional
@Table(name = "address", schema = "spr")
public class Address implements Serializable {

    @Column(name = "AddressId", table = "address", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long addressId;

    @Column(name = "AddressLine", table = "address")
    @Basic
    private String addressLine;

    @Column(name = "City", table = "address")
    @Basic
    private String city;

    @Column(name = "Country", table = "address")
    @Basic
    private String country;

    @Column(name = "PostalCode", table = "address")
    @Basic
    private String postalCode;

    @Column(name = "ModifiedDate", table = "address")
    @Basic
    private String modifiedDate;

    @OneToMany(targetEntity = Customer.class, mappedBy = "address1")
    private List<Customer> customers1;

    @OneToMany(targetEntity = Location.class, mappedBy = "address")
    private List<Location> locations;

}
