/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Getter
@Setter
@Transactional
@Table(name = "discountrule", schema = "spr")
public class Discountrule implements Serializable {

    @Column(name = "DRId", table = "discountrule", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long dRId;

    @Column(name = "DiscountValue", table = "discountrule", precision = 12)
    @Basic
    private Float discountValue;

    @Column(name = "DiscountProcent", table = "discountrule", precision = 12)
    @Basic
    private Float discountProcent;

    @Column(name = "Type", table = "discountrule", precision = 12)
    @Basic
    private String type;

    @Column(name = "Description", table = "discountrule")
    @Basic
    private String description;

    @OneToMany(targetEntity = Itemdiscount.class, mappedBy = "discountrule", cascade = CascadeType.REMOVE)
    private List<Itemdiscount> itemdiscounts;

    @OneToMany(targetEntity = OrdItemDiscount.class, mappedBy = "discountrule", cascade = CascadeType.REMOVE)
    private List<OrdItemDiscount> orditemdiscounts;

}
