/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Getter
@Setter
@Transactional
@Table(name = "itemdiscount", schema = "spr")
public class Itemdiscount implements Serializable {

    @Column(name = "IDid", table = "itemdiscount", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("IDid")
    private Long IDid;

    @ManyToOne(targetEntity = Item.class)
    private Item item1;

    @ManyToOne(targetEntity = Discountrule.class)
    private Discountrule discountrule;
}
