/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Getter
@Setter
@Transactional
@Table(name = "itemgroup", schema = "spr")
public class Itemgroup implements Serializable {

    @Column(name = "IGId", table = "itemgroup", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long iGId;

    @ManyToOne(targetEntity = Groups.class)
    private Groups groups1;

    @ManyToOne(targetEntity = Item.class)
    private Item item1;

}
