/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "paymenttype", schema = "spr")
@Getter
@Setter
@Transactional
public class Paymenttype implements Serializable {

    @Column(name = "PTId", table = "paymenttype", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long pTId;

    @Column(name = "TypeName", table = "paymenttype")
    @Basic
    private String typeName;

    @OneToMany(targetEntity = Payment.class, mappedBy = "paymenttype")
    private List<Payment> payments;
}
