/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "payment", schema = "spr")
@Getter
@Setter
@Transactional
public class Payment implements Serializable {

    @Column(name = "PaymentId", table = "payment", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long paymentId;

    @Column(name = "PaymentInfo", table = "payment")
    @Basic
    private String paymentInfo;

    @Column(name = "paymentDate", table = "payment")
    @Basic
    private Date paymentDate;

    @ManyToOne(targetEntity = Paymenttype.class)
    private Paymenttype paymenttype;

    @ManyToOne(targetEntity = So.class)
    private So so;

    @ManyToOne(targetEntity = Paymentbill.class)
    private Paymentbill paymentbill;

}
