/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "productitems", schema = "spr")
@Getter
@Setter
@Transactional
public class ProductItems implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "MP", table = "productitems", precision = 12)
    @Basic
    private Float mp;

    @Column(name = "OTP", table = "productitems", precision = 12)
    @Basic
    private Float otp;

    @Column(name = "MPWithTaxandDiscont", table = "productitems", precision = 12)
    @Basic
    private Float MPWithTaxandDiscont;

    @Column(name = "OTPWithTaxandDiscont", table = "productitems", precision = 12)
    @Basic
    private Float OTPWithTaxandDiscont;

    @ManyToOne(targetEntity = Soproduct.class)
    private Soproduct soproduct;

    @ManyToOne(targetEntity = OrdItem.class, cascade = CascadeType.REMOVE)
    private OrdItem ordItem;
}
