/**
 * This file was generated by the JPA Modeler
 */
package com.spr.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "statisticscollector", schema = "spr")
@Getter
@Setter
@Transactional
public class Statisticscollector implements Serializable {

    @Column(name = "SCId", table = "statisticscollector", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long SCId;

    @Column(name = "StatisticType", table = "statisticscollector")
    @Basic
    private String statisticType;

    @Column(name = "StatisticsInfo", table = "statisticscollector")
    @Basic
    private String statisticsInfo;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer;

}
